<?php

require_once(get_stylesheet_directory() . '/includes/core/const.php');
// Dynamiczna generacja grup pól na podstawie stałych
$acf_stats_group = [
    'key' => 'field_6793e6cb83c38',
    'label' => 'Statystyki',
    'name' => 'stats',
    'type' => 'group',
    'instructions' => 'Podstawowe statystyki gracza',
    'required' => 0,
    'conditional_logic' => 0,
    'layout' => 'block',
    'sub_fields' => [],
];

$acf_skills_group = [
    'key' => 'field_skills_group',
    'label' => 'Umiejętności',
    'name' => SKILLS['name'],
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => [],
];

$acf_progress_group = [
    'key' => 'field_progress_group',
    'label' => 'Postęp',
    'name' => PROGRESS['name'],
    'aria-label' => '',
    'type' => 'group',
    'instructions' => 'Kontener na progress gracza',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => [],
];

$acf_vitality_group = [
    'key' => 'field_vitality_group',
    'label' => 'Witalność',
    'name' => VITALITY['name'],
    'aria-label' => '',
    'type' => 'group',
    'instructions' => 'Kontener na witalność gracza',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => [],
];

$acf_backpack_group = [
    'key' => 'field_6793e69183c31',
    'label' => 'Plecak',
    'name' => BACKPACK['name'],
    'aria-label' => '',
    'type' => 'group',
    'instructions' => 'Kontener na przedmioty gracza',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'acfe_seamless_style' => 0,
    'acfe_group_modal' => 0,
    'acfe_group_modal_close' => 0,
    'acfe_group_modal_button' => '',
    'acfe_group_modal_size' => 'large',
    'sub_fields' => [],
];

// Generowanie pól dla STATS
foreach (STATS['fields'] as $stat_key => $data) {
    $acf_stats_group['sub_fields'][] = [
        'key' => 'field_stats_' . $stat_key,
        'label' => $data['label'],
        'name' => $stat_key,
        'type' => 'number',
        'instructions' => $data['instructions'],
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => $data['default'],
        'min' => 0,
        'step' => 1,
    ];
}

// Generowanie pól dla SKILLS
foreach (SKILLS['fields'] as $skill_key => $data) {
    $acf_skills_group['sub_fields'][] = [
        'key' => 'field_skills_' . $skill_key,
        'label' => $data['label'],
        'name' => $skill_key,
        'type' => 'number',
        'instructions' => $data['instructions'],
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => $data['default'],
        'min' => 0,
        'step' => 1,
    ];
}

// Generowanie pól dla PROGRESS
foreach (PROGRESS['fields'] as $progress_key => $data) {
    $acf_progress_group['sub_fields'][] = [
        'key' => 'field_progress_' . $progress_key,
        'label' => $data['label'],
        'name' => $progress_key,
        'type' => 'number',
        'instructions' => $data['instructions'],
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => $data['default'],
        'min' => ($progress_key === 'reputation') ? -100 : 0, // Specjalna obsługa dla reputacji
        'max' => ($progress_key === 'reputation') ? 100 : '',
        'step' => 1,
    ];
}

// Generowanie pól dla VITALITY
foreach (VITALITY['fields'] as $vitality_key => $data) {
    $acf_vitality_group['sub_fields'][] = [
        'key' => 'field_' . ($vitality_key === 'max_energy' ? '6793e6cb83c3b_max' : '6793e6cb83c3' . array_search($vitality_key, array_keys(VITALITY['fields']))),
        'label' => $data['label'],
        'name' => $vitality_key,
        'type' => 'number',
        'instructions' => $data['instructions'],
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => $data['default'],
        'min' => 0,
    ];
}

// Generowanie pól dla BACKPACK
foreach (BACKPACK['fields'] as $backpack_key => $data) {
    $acf_backpack_group['sub_fields'][] = [
        'key' => 'field_' . ($backpack_key === 'gold' ? '6793e6a783c33' : '6793e69b83c32'),
        'label' => $data['label'],
        'name' => $backpack_key,
        'aria-label' => '',
        'type' => 'number',
        'instructions' => $data['instructions'],
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => $data['default'],
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ];
}

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_user_settings',
        'title' => 'User',
        'fields' => array(
            array(
                'key' => 'field_tab_basic_info',
                'label' => 'Podstawowe informacje',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_679a2b8a1nick',
                'label' => 'Nick',
                'name' => 'nick',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Nazwa gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6794b4c86bae4',
                'label' => 'Avatar',
                'name' => 'avatar',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Obrazek postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50%',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'uploader' => '',
                'acfe_thumbnail' => 0,
            ),
            array(
                'key' => 'field_6794b4c86bae4_full',
                'label' => 'Avatar Full',
                'name' => 'avatar_full',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Pełny obrazek postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50%',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'medium',
                'min_width' => 0,
                'min_height' => 0,
                'min_size' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'max_size' => 0,
                'mime_types' => '',
                'uploader' => '',
                'acfe_thumbnail' => 0,
            ),
            array(
                'key' => 'field_679a2b8ab83a2',
                'label' => 'Story',
                'name' => 'story',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Tło fabularne postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_679a2d06adef9',
                'label' => 'Klasa',
                'name' => 'user_class',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'zadymiarz' => 'Zadymiarz',
                    'zawijacz' => 'Zawijacz',
                    'kombinator' => 'Kombinator',
                ),
                'default_value' => false,
                'return_format' => 'array',
                'multiple' => 0,
                'allow_null' => 1,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            array(
                'key' => 'field_tab_stats',
                'label' => 'Statystyki',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            $acf_stats_group,
            $acf_progress_group,
            $acf_vitality_group,
            array(
                'key' => 'field_tab_skills',
                'label' => 'Umiejętności',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            $acf_skills_group,
            array(
                'key' => 'field_tab_districts',
                'label' => 'Rejony',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_current_area',
                'label' => 'Aktualny rejon',
                'name' => 'current_area',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => 'Aktualna lokalizacja gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'tereny',
                ),
                'taxonomy' => '',
                'allow_null' => 1,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
                'bidirectional_target' => array(),
                'save_custom' => 0,
                'save_post_type' => '',
                'save_post_status' => '',
            ),
            array(
                'key' => 'field_available_areas',
                'label' => 'Dostępne rejony',
                'name' => 'available_areas',
                'aria-label' => '',
                'type' => 'checkbox',
                'instructions' => 'Zaznacz rejony dostępne dla gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    329 => 'Dostępny rejon Kolejowa',
                    207 => 'Dostępny rejon Park',
                    24 => 'Dostępny rejon start',
                ),
                'default_value' => array(),
                'return_format' => 'value',
                'allow_custom' => 0,
                'layout' => 'vertical',
                'save_custom' => 0,
                'custom_choice_button_text' => 'Dodaj nowy wybór',
                'toggle' => 0,
            ),
            array(
                'key' => 'field_tab_equipped_items',
                'label' => 'Przedmioty',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            $acf_backpack_group,
            array(
                'key' => 'field_equipped_items_group',
                'label' => 'Założone przedmioty',
                'name' => 'equipped_items',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Przedmioty aktualnie założone przez gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_equipped_item_chest',
                        'label' => 'Na klatę',
                        'name' => 'chest_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na klatę',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:3',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                    array(
                        'key' => 'field_equipped_item_bottom',
                        'label' => 'Na poślady',
                        'name' => 'bottom_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na poślady',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:4',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                    array(
                        'key' => 'field_equipped_item_legs',
                        'label' => 'Na giczuły',
                        'name' => 'legs_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na giczuły',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:7',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_items_inventory',
                'label' => 'Przedmioty',
                'name' => 'items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => 'Lista przedmiotów posiadanych przez gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Dodaj przedmiot',
                'rows_per_page' => 20,
                'acfe_repeater_stylised_button' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_item_relation',
                        'label' => 'Przedmiot',
                        'name' => 'item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                        'parent_repeater' => 'field_items_inventory',
                    ),
                    array(
                        'key' => 'field_item_quantity',
                        'label' => 'Ilość',
                        'name' => 'quantity',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 1,
                        'max' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_items_inventory',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_role',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => array(
            0 => 'php',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
        'modified' => 1746461798,
    ));

endif;
