<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_start_rozmowy',
		'title' => 'Start Rozmowy',
		'fields' => array(
			array(
				'key' => 'field_67b08ae59dc59',
				'label' => 'Start rozmowy',
				'name' => 'conversation_start',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => false,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Dodaj warunek',
				'layouts' => array(
					'layout_warunek' => array(
						'key' => 'layout_warunek',
						'name' => 'warunek',
						'label' => 'Warunek',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_67b08af09dc5a',
								'label' => 'Jeśli',
								'name' => 'if',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => false,
								'conditional_logic' => false,
								'wrapper' => array(
									'width' => '20',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'mission' => 'Misja',
									'scena' => 'Scena',
									'instance' => 'Instancja',
									'relation' => 'Relacja',
								),
								'default_value' => false,
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'allow_custom' => 0,
								'search_placeholder' => '',
							),
							array(
								'key' => 'field_67b08fcbf1563',
								'label' => 'Misja',
								'name' => 'mission_select',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_67b08af09dc5a',
											'operator' => '==',
											'value' => 'mission',
										),
									),
								),
								'wrapper' => array(
									'width' => '80',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'acfe_seamless_style' => 0,
								'acfe_group_modal' => 0,
								'sub_fields' => array(
									array(
										'key' => 'field_67b08ba89dc5b',
										'label' => 'Misja',
										'name' => 'mission',
										'aria-label' => '',
										'type' => 'post_object',
										'instructions' => '',
										'required' => false,
										'conditional_logic' => false,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'mission',
										),
										'return_format' => 'id',
										'ui' => 0,
										'taxonomy' => array(),
										'allow_null' => 0,
										'multiple' => 0,
										'bidirectional_target' => array(),
										'save_custom' => 0,
										'save_post_type' => '',
										'save_post_status' => '',
									),
									array(
										'key' => 'field_mission_task_id_condition',
										'label' => 'Zadanie',
										'name' => 'mission_task_id',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => 'Zadania załadują się po wybraniu misji',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array(),
										'default_value' => '',
										'allow_null' => 1,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 1,
										'save_custom' => 1,
										'placeholder' => 'Wybierz zadanie',
									),
									array(
										'key' => 'field_task_status_condition',
										'label' => 'Status zadania',
										'name' => 'task_status',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_mission_task_id_condition',
													'operator' => '!=empty',
													'value' => '',
												),
											),
										),
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'not_started' => 'Niezaczęte',
											'in_progress' => 'Rozpoczęte',
											'completed' => 'Ukończone',
											'failed' => 'Niepowodzenie',
										),
										'default_value' => 'in_progress',
										'ui' => 0,
										'ajax' => 0,
										'placeholder' => '',
										'allow_null' => 0,
										'multiple' => 0,
										'return_format' => 'value',
										'save_custom' => 0,
									),
									array(
										'key' => 'field_67b08e96fffbe',
										'label' => 'Status całej misji',
										'name' => 'mission_status',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => false,
										'conditional_logic' => false,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'not_started' => 'Niezaczęta',
											'in_progress' => 'Rozpoczęta',
											'completed' => 'Ukończona',
										),
										'default_value' => '0',
										'ui' => 0,
										'return_format' => 'value',
										'multiple' => 0,
										'allow_null' => 0,
									),
								),
								'acfe_group_modal_close' => 0,
								'acfe_group_modal_button' => '',
								'acfe_group_modal_size' => 'large',
							),
							array(
								'key' => 'field_67b08bc79dc5c',
								'label' => 'Scena',
								'name' => 'scena',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_67b08af09dc5a',
											'operator' => '==',
											'value' => 'scena',
										),
									),
								),
								'wrapper' => array(
									'width' => '80',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 1,
								'placeholder' => '',
								'prepend' => 'jest równa',
								'append' => '',
							),
							array(
								'key' => 'field_67b08c0c9dc5d',
								'label' => 'Instancja',
								'name' => 'instation',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_67b08af09dc5a',
											'operator' => '==',
											'value' => 'instance',
										),
									),
								),
								'wrapper' => array(
									'width' => '80',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 1,
								'placeholder' => '',
								'prepend' => 'jest równa',
								'append' => '',
							),
							array(
								'key' => 'field_67b0901df1565',
								'label' => 'Relacja',
								'name' => 'relation_select',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_67b08af09dc5a',
											'operator' => '==',
											'value' => 'relation',
										),
									),
								),
								'wrapper' => array(
									'width' => '80',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'acfe_seamless_style' => 0,
								'acfe_group_modal' => 0,
								'sub_fields' => array(
									array(
										'key' => 'field_67b08c2b9dc5e',
										'label' => 'Relacja',
										'name' => 'relacja',
										'aria-label' => '',
										'type' => 'post_object',
										'instructions' => '',
										'required' => false,
										'conditional_logic' => false,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'post_type' => array(
											0 => 'npc',
										),
										'return_format' => 'id',
										'ui' => 1,
										'taxonomy' => array(),
										'allow_null' => 0,
										'multiple' => 0,
										'bidirectional_target' => array(),
										'save_custom' => 0,
										'save_post_type' => '',
										'save_post_status' => '',
									),
									array(
										'key' => 'field_67b08c829dc5f',
										'label' => 'Operator',
										'name' => 'operator',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => false,
										'conditional_logic' => false,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'>' => '>',
											'>=' => '>=',
											'=' => '=',
											'<' => '<',
											'=>' => '=>',
											'exist' => 'Jest',
										),
										'default_value' => false,
										'return_format' => 'value',
										'multiple' => 0,
										'allow_null' => 0,
										'ui' => 0,
										'ajax' => 0,
										'placeholder' => '',
										'allow_custom' => 0,
										'search_placeholder' => '',
									),
									array(
										'key' => 'field_67b08cab9dc60',
										'label' => 'Wartość',
										'name' => 'value',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => false,
										'conditional_logic' => false,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'maxlength' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
									),
								),
								'acfe_group_modal_close' => 0,
								'acfe_group_modal_button' => '',
								'acfe_group_modal_size' => 'large',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style' => false,
						'acfe_flexible_render_script' => false,
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
				),
				'min' => 0,
				'max' => 0,
				'acfe_flexible_advanced' => false,
				'acfe_flexible_stylised_button' => false,
				'acfe_flexible_hide_empty_message' => false,
				'acfe_flexible_empty_message' => '',
				'acfe_flexible_layouts_templates' => false,
				'acfe_flexible_layouts_previews' => false,
				'acfe_flexible_layouts_placeholder' => false,
				'acfe_flexible_layouts_thumbnails' => false,
				'acfe_flexible_layouts_settings' => false,
				'acfe_flexible_async' => array(),
				'acfe_flexible_add_actions' => array(),
				'acfe_flexible_remove_button' => array(),
				'acfe_flexible_layouts_state' => false,
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => false,
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => false,
					'acfe_flexible_modal_title' => false,
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '4',
					'acfe_flexible_modal_categories' => false,
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '!=',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => 'group_npc',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1739985323,
	));

endif;
