<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_item',
		'title' => 'Dodatkowe informacje o przedmiocie',
		'fields' => array(
			array(
				'key' => 'field_item_description',
				'label' => 'Opis przedmiotu',
				'name' => 'item_description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Krótki opis przedmiotu',
				'required' => 1,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'new_lines' => '',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => '',
				'acfe_textarea_code' => 0,
			),
			array(
				'key' => 'field_item_value',
				'label' => 'Wartość',
				'name' => 'item_value',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => 'Wartość przedmiotu',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_item_weight',
				'label' => 'Waga',
				'name' => 'item_weight',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => 'Waga przedmiotu w kg',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_item_durability',
				'label' => 'Wytrzymałość',
				'name' => 'item_durability',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => 'Wytrzymałość przedmiotu (jeśli dotyczy)',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 100,
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_item_stats',
				'label' => 'Statystyki',
				'name' => 'item_stats',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Jakie statystyki zwiększa przedmiot',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'button_label' => 'Dodaj statystykę',
				'min' => 0,
				'max' => 0,
				'rows_per_page' => 20,
				'collapsed' => '',
				'acfe_repeater_stylised_button' => 0,
				'sub_fields' => array(
					array(
						'key' => 'field_stat_type',
						'label' => 'Typ statystyki',
						'name' => 'stat_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'strength' => 'Siła (obrażenia w walce wręcz, dominacja w bójkach)',
							'vitality' => 'Wytrzymałość (życie, odporność na używki, obrażenia)',
							'dexterity' => 'Zręczność (kradzież, uniki, ucieczki)',
							'perception' => 'Percepcja (wykrywanie ukrytych elementów)',
							'technical' => 'Zdolności manualne (produkcja, hakowanie, techniczne akcje)',
							'charisma' => 'Cwaniactwo (bajerowanie NPC, układy, handel)',
						),
						'default_value' => 'strength',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'return_format' => 'value',
						'allow_custom' => 0,
						'search_placeholder' => '',
						'parent_repeater' => 'field_item_stats',
					),
					array(
						'key' => 'field_stat_value',
						'label' => 'Wartość bonusu',
						'name' => 'stat_value',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'min' => 0,
						'max' => '',
						'step' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_item_stats',
					),
				),
			),
			array(
				'key' => 'field_item_skills',
				'label' => 'Umiejętności',
				'name' => 'item_skills',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Jakie umiejętności zwiększa przedmiot',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'button_label' => 'Dodaj umiejętność',
				'min' => 0,
				'max' => 0,
				'rows_per_page' => 20,
				'collapsed' => '',
				'acfe_repeater_stylised_button' => 0,
				'sub_fields' => array(
					array(
						'key' => 'field_skill_type',
						'label' => 'Typ umiejętności',
						'name' => 'skill_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'combat' => 'Walka',
							'steal' => 'Kradzież',
							'craft' => 'Produkcja',
							'trade' => 'Handel',
							'relations' => 'Relacje',
							'street' => 'Uliczna wiedza',
							'technical' => 'Zdolności manualne',
							'charisma' => 'Cwaniactwo',
						),
						'default_value' => 'combat',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'return_format' => 'value',
						'allow_custom' => 0,
						'search_placeholder' => '',
						'parent_repeater' => 'field_item_skills',
					),
					array(
						'key' => 'field_skill_value',
						'label' => 'Wartość',
						'name' => 'skill_value',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'min' => 0,
						'max' => '',
						'step' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_item_skills',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'item',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1746462267,
	));

endif;
