<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_tereny',
		'title' => 'Dane Terenów',
		'fields' => array(
			array(
				'key' => 'field_teren_opis',
				'label' => 'Opis Terenu',
				'name' => 'teren_opis',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => false,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'new_lines' => 'br',
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'rows' => '',
				'acfe_textarea_code' => 0,
			),
			array(
				'key' => 'field_67ffcb196ea22',
				'label' => 'Zdarzenia',
				'name' => '',
				'aria-label' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_67b0b36aea475',
				'label' => 'Zdarzenia',
				'name' => 'events',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Dodaj zdarzenie',
				'rows_per_page' => 20,
				'acfe_repeater_stylised_button' => 0,
				'sub_fields' => array(
					array(
						'key' => 'field_67b0b40aea479',
						'label' => 'Zdarzenie',
						'name' => 'event',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_67b0b399ea477',
									'operator' => '==',
									'value' => 'event',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'events',
						),
						'post_status' => '',
						'taxonomy' => '',
						'return_format' => 'id',
						'multiple' => 0,
						'allow_null' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_67b0b36aea475',
						'save_custom' => 0,
						'save_post_type' => '',
						'save_post_status' => '',
					),
					array(
						'key' => 'field_67b0b3fcea478',
						'label' => 'Liczba zdarzeń',
						'name' => 'liczba_zdarzen',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => 0,
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_67b0b36aea475',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tereny',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'acfe_display_title' => '',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1746462888,
	));

endif;
