<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_mission',
		'title' => 'Misje',
		'fields' => array(
			array(
				'key' => 'field_mission_description',
				'label' => 'Opis misji',
				'name' => 'mission_description',
				'type' => 'textarea',
				'instructions' => 'Krótki opis misji',
				'required' => 1,
				'rows' => 5,
				'new_lines' => 'br',
				'placeholder' => '',
			),

			array(
				'key' => 'field_mission_time_limit',
				'label' => 'Limit czasowy',
				'name' => 'mission_time_limit',
				'type' => 'number',
				'instructions' => 'Limit czasowy w godzinach (0 = bez limitu)',
				'required' => 0,
				'min' => 0,
				'max' => 168,
				'default_value' => 0,
				'step' => 1,
			),
			array(
				'key' => 'field_mission_type',
				'label' => 'Typ misji',
				'name' => 'mission_type',
				'type' => 'select',
				'instructions' => 'Wybierz typ misji (jak często może być wykonywana)',
				'required' => 1,
				'choices' => array(
					'one-time' => 'Jednorazowa',
					'daily' => 'Dzienna',
					'weekly' => 'Tygodniowa',
				),
				'default_value' => 'one-time',
				'ui' => 1,
				'return_format' => 'value',
				'allow_null' => 0,
				'multiple' => 0,
				'search_placeholder' => 'Wybierz typ misji',
				'allow_custom' => 0,
			),
			array(
				'key' => 'field_mission_tasks',
				'label' => 'Zadania',
				'name' => 'mission_tasks',
				'type' => 'repeater',
				'instructions' => 'Lista zadań do wykonania w tej misji',
				'required' => 1,
				'min' => 1,
				'layout' => 'block',
				'button_label' => 'Dodaj zadanie',
				'collapsed' => 'field_task_title',
				'acfe_repeater_stylised_button' => 1,
				'sub_fields' => array(
					array(
						'key' => 'field_task_id',
						'label' => 'ID zadania',
						'name' => 'task_id',
						'type' => 'acfe_slug',
						'instructions' => 'Unikalny identyfikator zadania (slug)',
						'required' => 1,
						'wrapper' => array(
							'width' => '50',
						),
					),
					array(
						'key' => 'field_task_title',
						'label' => 'Tytuł zadania',
						'name' => 'task_title',
						'type' => 'text',
						'instructions' => 'Nazwa zadania widoczna dla gracza',
						'required' => 1,
						'wrapper' => array(
							'width' => '50',
						),
					),
					array(
						'key' => 'field_task_description',
						'label' => 'Opis zadania',
						'name' => 'task_description',
						'type' => 'textarea',
						'instructions' => 'Szczegółowy opis zadania',
						'rows' => 3,
					),
					array(
						'key' => 'field_task_optional',
						'label' => 'Opcjonalne',
						'name' => 'task_optional',
						'type' => 'true_false',
						'instructions' => 'Czy zadanie jest opcjonalne?',
						'default_value' => 0,
						'ui' => 1,
						'wrapper' => array(
							'width' => '50',
						),
					),
					array(
						'key' => 'field_task_attempt_limit',
						'label' => 'Limit prób',
						'name' => 'task_attempt_limit',
						'type' => 'number',
						'instructions' => 'Maksymalna liczba prób wykonania zadania (0 = bez limitu)',
						'required' => 0,
						'default_value' => 0,
						'min' => 0,
						'max' => 100,
						'step' => 1,
						'wrapper' => array(
							'width' => '50',
						),
					),
					array(
						'key' => 'field_task_type',
						'label' => 'Typ zadania',
						'name' => 'task_type',
						'type' => 'select',
						'instructions' => 'Wybierz typ zadania',
						'required' => 1,
						'choices' => array(
							'checkpoint' => 'Checkpoint (miejsce)',
							'checkpoint_npc' => 'Rozmowa z NPC',
							'defeat_enemies' => 'Pokonaj przeciwników',
						),
						'default_value' => 'checkpoint',
						'ui' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
						'multiple' => 0,
						'ajax' => 0,
						'search_placeholder' => 'Szukaj typu zadania',
						'allow_custom' => 0,
					),
					// Checkpoint - miejsce
					array(
						'key' => 'field_task_location',
						'label' => 'Lokalizacja',
						'name' => 'task_location',
						'type' => 'post_object',
						'instructions' => 'Wybierz lokalizację (teren lub event)',
						'post_type' => array('tereny', 'events'),
						'return_format' => 'id',
						'ui' => 1,
						'allow_null' => 0,
						'save_custom' => 0,
						'wrapper' => array(
							'width' => '50',
						),
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'checkpoint',
								),
							),
						),
					),
					// Pole wyboru konkretnej sceny (jeśli istnieje)
					array(
						'key' => 'field_task_location_scene',
						'label' => 'Konkretna scena',
						'name' => 'task_location_scene',
						'type' => 'text',
						'instructions' => 'Wpisz ID konkretnej sceny (opcjonalnie). Pozostaw puste, aby uznać zadanie za wykonane po wejściu na teren/event.',
						'placeholder' => 'np. main, scene_1, itd.',
						'wrapper' => array(
							'width' => '50',
						),
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'checkpoint',
								),
							),
						),
					),
					// NPC do rozmowy
					array(
						'key' => 'field_task_checkpoint_npc',
						'label' => 'NPC do zadania',
						'name' => 'task_checkpoint_npc',
						'type' => 'repeater',
						'instructions' => 'Lista NPC powiązanych z tym zadaniem',
						'layout' => 'table',
						'button_label' => 'Dodaj NPC',
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'checkpoint_npc',
								),
							),
						),
						'sub_fields' => array(
							array(
								'key' => 'field_task_checkpoint_npc_select',
								'label' => 'NPC',
								'name' => 'npc',
								'type' => 'post_object',
								'post_type' => array('npc'),
								'return_format' => 'id',
								'ui' => 1,
								'allow_null' => 0,
								'required' => 1,
								'save_custom' => 0,
							),
							array(
								'key' => 'field_task_checkpoint_npc_status',
								'label' => 'Status',
								'name' => 'status',
								'type' => 'select',
								'choices' => array(
									'not_started' => 'Niezaczęte',
									'in_progress' => 'W trakcie',
									'completed' => 'Ukończone',
									'failed' => 'Nieudane',
								),
								'default_value' => 'completed',
								'ui' => 1,
								'return_format' => 'value',
								'allow_null' => 0,
								'multiple' => 0,
								'ajax' => 0,
								'search_placeholder' => 'Szukaj statusu',
								'allow_custom' => 0,
							),
						),
					),
					// Pokonanie przeciwników
					array(
						'key' => 'field_task_defeat_enemies',
						'label' => 'Przeciwnicy do pokonania',
						'name' => 'task_defeat_enemies',
						'type' => 'post_object',
						'instructions' => 'Wybierz NPC do pokonania',
						'post_type' => array('npc'),
						'multiple' => 1,
						'return_format' => 'id',
						'ui' => 1,
						'allow_null' => 0,
						'save_custom' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'defeat_enemies',
								),
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'mission',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => time(),
	));

endif;
