<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_mission',
		'title' => 'Misje',
		'fields' => array(
			array(
				'key' => 'field_mission_description',
				'label' => 'Opis misji',
				'name' => 'mission_description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Krótki opis misji',
				'required' => 1,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'rows' => 5,
				'new_lines' => 'br',
				'maxlength' => '',
				'placeholder' => '',
				'acfe_textarea_code' => 0,
			),
			array(
				'key' => 'field_mission_tasks',
				'label' => 'Zadania',
				'name' => 'mission_tasks',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Lista zadań do wykonania w tej misji',
				'required' => 0,
				'conditional_logic' => false,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_repeater_stylised_button' => 1,
				'layout' => 'block',
				'button_label' => 'Dodaj zadanie',
				'min' => 0,
				'max' => 0,
				'rows_per_page' => 20,
				'collapsed' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_task_title',
						'label' => 'Nazwa zadania',
						'name' => 'task_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Krótka nazwa zadania',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_mission_tasks',
					),
					array(
						'key' => 'field_task_description',
						'label' => 'Opis zadania',
						'name' => 'task_description',
						'aria-label' => '',
						'type' => 'textarea',
						'instructions' => 'Szczegółowy opis zadania',
						'required' => 0,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_textarea_code' => 0,
						'rows' => 3,
						'default_value' => '',
						'new_lines' => '',
						'maxlength' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_mission_tasks',
					),
					array(
						'key' => 'field_task_type',
						'label' => 'Typ zadania',
						'name' => 'task_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => 'Wybierz typ zadania',
						'required' => 1,
						'conditional_logic' => false,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'allow_custom' => 0,
						'search_placeholder' => 'Wybierz typ zadania',
						'choices' => array(
							'place' => 'Odwiedź miejsce',
							'checkpoint' => 'Zalicz checkpoint',
							'checkpoint_npc' => 'Zalicz checkpoint z NPC',
						),
						'default_value' => 'place',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'return_format' => 'value',
						'parent_repeater' => 'field_mission_tasks',
					),
					array(
						'key' => 'field_task_place_id',
						'label' => 'ID miejsca',
						'name' => 'task_place_id',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Wprowadź identyfikator miejsca do odwiedzenia',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'place',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_mission_tasks',
					),
					array(
						'key' => 'field_task_checkpoint',
						'label' => 'ID checkpointu',
						'name' => 'task_checkpoint',
						'aria-label' => '',
						'type' => 'acfe_slug',
						'instructions' => 'Wprowadź identyfikator checkpointu do zaliczenia',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'checkpoint',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_mission_tasks',
					),
					array(
						'key' => 'field_task_checkpoint_npc',
						'label' => 'NPC do zadania',
						'name' => 'task_checkpoint_npc',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => 'Lista NPC powiązana z tym zadaniem',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_task_type',
									'operator' => '==',
									'value' => 'checkpoint_npc',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'table',
						'button_label' => 'Dodaj NPC',
						'min' => 0,
						'max' => 0,
						'rows_per_page' => 20,
						'collapsed' => '',
						'parent_repeater' => 'field_mission_tasks',
						'sub_fields' => array(
							array(
								'key' => 'field_task_checkpoint_npc_select',
								'label' => 'Wybierz NPC',
								'name' => 'npc',
								'aria-label' => '',
								'type' => 'post_object',
								'instructions' => 'Wybierz NPC z listy',
								'required' => 1,
								'conditional_logic' => false,
								'wrapper' => array(
									'width' => '60',
									'class' => '',
									'id' => '',
								),
								'search_placeholder' => 'Wybierz NPC',
								'save_custom' => 0,
								'post_type' => array(
									0 => 'npc',
								),
								'return_format' => 'id',
								'taxonomy' => array(),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 1,
								'bidirectional_target' => array(),
								'parent_repeater' => 'field_task_checkpoint_npc',
								'save_post_type' => '',
								'save_post_status' => '',
							),
							array(
								'key' => 'field_task_checkpoint_npc_status',
								'label' => 'Status',
								'name' => 'status',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => 'Wybierz status dla tego NPC',
								'required' => 1,
								'conditional_logic' => false,
								'wrapper' => array(
									'width' => '40',
									'class' => '',
									'id' => '',
								),
								'search_placeholder' => 'Wybierz status',
								'allow_custom' => 0,
								'choices' => array(
									'not_started' => 'Niezaczęte',
									'in_progress' => 'Rozpoczęte',
									'completed' => 'Ukończone',
									'failed' => 'Niepowodzenie',
								),
								'default_value' => 'not_started',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'return_format' => 'value',
								'parent_repeater' => 'field_task_checkpoint_npc',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'mission',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1746462400,
	));

endif;
