<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_npc',
		'title' => 'Dane NPC',
		'fields' => array(
			array(
				'key' => 'field_67b4d8085d3ab',
				'label' => 'Dialog',
				'name' => 'anwser',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'acfe_flexible_advanced' => 1,
				'acfe_flexible_stylised_button' => 1,
				'acfe_flexible_layouts_templates' => 1,
				'acfe_flexible_layouts_previews' => 0,
				'acfe_flexible_layouts_placeholder' => 0,
				'acfe_flexible_layouts_thumbnails' => 1,
				'acfe_flexible_layouts_settings' => 1,
				'acfe_flexible_async' => array(
					0 => 'title',
				),
				'acfe_flexible_add_actions' => array(
					0 => 'title',
					1 => 'toggle',
					2 => 'close',
				),
				'acfe_flexible_remove_button' => array(),
				'acfe_flexible_layouts_state' => 'user',
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => '0',
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => '0',
					'acfe_flexible_modal_title' => false,
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '4',
					'acfe_flexible_modal_categories' => false,
				),
				'layouts' => array(
					'layout_67b4dae46e98c' => array(
						'key' => 'layout_67b4dae46e98c',
						'name' => 'question',
						'label' => 'Dialog',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_67b4ddcb75ddc',
								'label' => 'ID pola',
								'name' => 'id_pola',
								'aria-label' => '',
								'type' => 'acfe_slug',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
							),
							array(
								'key' => 'field_67b4dcff497d5',
								'label' => 'Pytanie',
								'name' => 'question',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'allow_in_bindings' => 0,
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_67b4e72eec415',
								'label' => 'Odpowiedzi',
								'name' => 'anwsers',
								'aria-label' => '',
								'type' => 'flexible_content',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_flexible_advanced' => 1,
								'acfe_flexible_stylised_button' => 0,
								'acfe_flexible_hide_empty_message' => 0,
								'acfe_flexible_empty_message' => '',
								'acfe_flexible_layouts_templates' => 1,
								'acfe_flexible_layouts_previews' => 0,
								'acfe_flexible_layouts_placeholder' => 0,
								'acfe_flexible_layouts_thumbnails' => 0,
								'acfe_flexible_layouts_settings' => 1,
								'acfe_flexible_async' => array(),
								'acfe_flexible_add_actions' => array(),
								'acfe_flexible_remove_button' => array(),
								'acfe_flexible_layouts_state' => 'user',
								'acfe_flexible_modal_edit' => array(
									'acfe_flexible_modal_edit_enabled' => '0',
									'acfe_flexible_modal_edit_size' => 'large',
								),
								'acfe_flexible_modal' => array(
									'acfe_flexible_modal_enabled' => '0',
									'acfe_flexible_modal_title' => false,
									'acfe_flexible_modal_size' => 'full',
									'acfe_flexible_modal_col' => '4',
									'acfe_flexible_modal_categories' => false,
								),
								'layouts' => array(
									'layout_67b4e78c15feb' => array(
										'key' => 'layout_67b4e78c15feb',
										'name' => 'anwser',
										'label' => 'Odpowiedź',
										'display' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_67b4e7a2ec416',
												'label' => 'Treść odpowiedzi',
												'name' => 'anwser_text',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '30',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'maxlength' => '',
												'allow_in_bindings' => 0,
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
											),
											array(
												'key' => 'field_67b4ea1e2acbb',
												'label' => 'Typ odpowiedzi',
												'name' => 'type_anwser',
												'aria-label' => '',
												'type' => 'flexible_content',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'acfe_flexible_advanced' => 1,
												'acfe_flexible_stylised_button' => 0,
												'acfe_flexible_hide_empty_message' => 1,
												'acfe_flexible_layouts_templates' => 1,
												'acfe_flexible_layouts_previews' => 0,
												'acfe_flexible_layouts_placeholder' => 0,
												'acfe_flexible_layouts_thumbnails' => 0,
												'acfe_flexible_layouts_settings' => 0,
												'acfe_flexible_async' => array(),
												'acfe_flexible_add_actions' => array(
													0 => 'toggle',
													1 => 'close',
												),
												'acfe_flexible_remove_button' => array(),
												'acfe_flexible_modal_edit' => array(
													'acfe_flexible_modal_edit_enabled' => '1',
													'acfe_flexible_modal_edit_size' => 'xlarge',
												),
												'acfe_flexible_modal' => array(
													'acfe_flexible_modal_enabled' => '0',
													'acfe_flexible_modal_title' => false,
													'acfe_flexible_modal_size' => 'full',
													'acfe_flexible_modal_col' => '4',
													'acfe_flexible_modal_categories' => false,
												),
												'layouts' => array(
													'layout_67b4ea25717d1' => array(
														'key' => 'layout_67b4ea25717d1',
														'name' => 'transaction',
														'label' => 'Transakcja',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_67b4f2784d5e1',
																'label' => 'Waluta',
																'name' => 'bag',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'gold' => 'Hajs',
																	'papierosy' => 'Szlugi',
																	'piwo' => 'Browar',
																	'bimber' => 'Bimber',
																	'marihuana' => 'Marihuana',
																	'grzyby' => 'Grzyby',
																	'klej' => 'Klej',
																),
																'default_value' => false,
																'return_format' => '',
																'multiple' => 0,
																'allow_null' => 0,
																'allow_in_bindings' => 0,
																'ui' => 0,
																'ajax' => 0,
																'placeholder' => '',
																'allow_custom' => 0,
																'search_placeholder' => '',
															),
															array(
																'key' => 'field_67b4f2ba4d5e2',
																'label' => 'Wartość',
																'name' => 'value',
																'aria-label' => '',
																'type' => 'number',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'min' => '',
																'max' => '',
																'allow_in_bindings' => 0,
																'placeholder' => '',
																'step' => '',
																'prepend' => '',
																'append' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
													'layout_67b4f3848eb2d' => array(
														'key' => 'layout_67b4f3848eb2d',
														'name' => 'stats',
														'label' => 'Statystyki',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_67b4f3848eb2e',
																'label' => 'Typ statystyki',
																'name' => 'type_of_stats',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'life' => 'Życie',
																	'max_life' => 'Maksymalne życie',
																	'energy' => 'Energia',
																	'max_energy: Energia' => 'max_energy: Energia',
																),
																'default_value' => false,
																'return_format' => 'value',
																'multiple' => 0,
																'allow_null' => 0,
																'allow_in_bindings' => 0,
																'ui' => 0,
																'ajax' => 0,
																'placeholder' => '',
																'allow_custom' => 0,
																'search_placeholder' => '',
															),
															array(
																'key' => 'field_67b4f3848eb2f',
																'label' => 'Wartość',
																'name' => 'value',
																'aria-label' => '',
																'type' => 'number',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'min' => '',
																'max' => '',
																'allow_in_bindings' => 0,
																'placeholder' => '',
																'step' => '',
																'prepend' => '',
																'append' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
													'layout_67b4edfad07bb' => array(
														'key' => 'layout_67b4edfad07bb',
														'name' => 'relation',
														'label' => 'Relacja',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_67b4f19d4d5dd',
																'label' => 'NPC',
																'name' => 'npc',
																'aria-label' => '',
																'type' => 'post_object',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'post_type' => array(
																	0 => 'npc',
																),
																'post_status' => '',
																'taxonomy' => '',
																'return_format' => 'id',
																'multiple' => 0,
																'save_custom' => 0,
																'save_post_status' => 'publish',
																'acfe_bidirectional' => array(
																	'acfe_bidirectional_enabled' => '0',
																),
																'allow_null' => 0,
																'allow_in_bindings' => 0,
																'bidirectional' => 0,
																'ui' => 1,
																'bidirectional_target' => array(),
																'save_post_type' => '',
															),
															array(
																'key' => 'field_67b4f1c44d5de',
																'label' => 'Zmień relację o',
																'name' => 'change_relation',
																'aria-label' => '',
																'type' => 'range',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '50',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => 0,
																'min' => -100,
																'max' => 100,
																'allow_in_bindings' => 0,
																'step' => '',
																'prepend' => '',
																'append' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
													'layout_67b4ee4bd07bd' => array(
														'key' => 'layout_67b4ee4bd07bd',
														'name' => 'function',
														'label' => 'Funkcja',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_67b4ef5f6a17f',
																'label' => 'Funkcja',
																'name' => 'do_function',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'SetClass' => 'Wybierz klasę',
																	'go-to-page' => 'Przejdź do podstrony',
																),
																'default_value' => false,
																'return_format' => 'value',
																'multiple' => 0,
																'allow_null' => 0,
																'allow_in_bindings' => 1,
																'ui' => 0,
																'ajax' => 0,
																'placeholder' => '',
																'allow_custom' => 0,
																'search_placeholder' => '',
															),
															array(
																'key' => 'field_68013a77aaa4b',
																'label' => 'Url po slash',
																'name' => 'page_url',
																'aria-label' => '',
																'type' => 'text',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => array(
																	array(
																		array(
																			'field' => 'field_67b4ef5f6a17f',
																			'operator' => '==',
																			'value' => 'go-to-page',
																		),
																	),
																),
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'maxlength' => '',
																'allow_in_bindings' => 0,
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
													'layout_67b4f17f4d5db' => array(
														'key' => 'layout_67b4f17f4d5db',
														'name' => 'mission',
														'label' => 'Misja',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_mission_id',
																'label' => 'Wybierz misję',
																'name' => 'mission_id',
																'aria-label' => '',
																'type' => 'post_object',
																'instructions' => 'Wybierz misję, która zostanie aktywowana przez NPC',
																'required' => 1,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '25',
																	'class' => '',
																	'id' => '',
																),
																'post_type' => array(
																	0 => 'mission',
																),
																'taxonomy' => '',
																'allow_null' => 1,
																'multiple' => 0,
																'return_format' => 'id',
																'ui' => 1,
															),
															// Dodane pole statusu misji
															array(
																'key' => 'field_mission_status',
																'label' => 'Status misji',
																'name' => 'mission_status',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => 'Wybierz status misji',
																'required' => 0,
																'conditional_logic' => array(
																	array(
																		array(
																			'field' => 'field_mission_id',
																			'operator' => '!=empty',
																		),
																	),
																),
																'wrapper' => array(
																	'width' => '25',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'not_started' => 'Niezaczęte',
																	'in_progress' => 'Rozpoczęte',
																	'completed' => 'Ukończone',
																	'failed' => 'Niepowodzenie',
																),
																'default_value' => 'not_started',
																'allow_null' => 0,
																'multiple' => 0,
																'ui' => 1,
																'ajax' => 0,
																'return_format' => 'value',
																'placeholder' => '',
															),
															// Dodane pole wyboru zadania powiązanego z misją
															array(
																'key' => 'field_mission_task_id',
																'label' => 'Wybierz zadanie z misji',
																'name' => 'mission_task_id',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => 'Wybierz zadanie powiązane z wybraną misją',
																'required' => 0,
																'conditional_logic' => array(
																	array(
																		array(
																			'field' => 'field_mission_id',
																			'operator' => '!=empty',
																		),
																	),
																),
																'wrapper' => array(
																	'width' => '25',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(),
																'default_value' => '',
																'allow_null' => 1,
																'multiple' => 0,
																'ui' => 0,
																'ajax' => 0,
																'save_custom' => 1,
																'placeholder' => 'Wybierz zadanie z misji',
															),
															// Dodane pole statusu zadania
															array(
																'key' => 'field_mission_task_status',
																'label' => 'Status zadania',
																'name' => 'mission_task_status',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => 'Wybierz status zadania',
																'required' => 0,
																'conditional_logic' => array(
																	array(
																		array(
																			'field' => 'field_mission_task_id',
																			'operator' => '!=empty',
																		),
																	),
																),
																'wrapper' => array(
																	'width' => '25',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'not_started' => 'Niezaczęte',
																	'in_progress' => 'Rozpoczęte',
																	'completed' => 'Ukończone',
																	'failed' => 'Niepowodzenie',
																),
																'default_value' => 'not_started',
																'allow_null' => 0,
																'multiple' => 0,
																'ui' => 0,
																'ajax' => 0,
																'return_format' => 'value',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
													'layout_item_management' => array(
														'key' => 'layout_item_management',
														'name' => 'item',
														'label' => 'Przedmiot',
														'display' => 'block',
														'sub_fields' => array(
															array(
																'key' => 'field_item_action',
																'label' => 'Akcja',
																'name' => 'item_action',
																'aria-label' => '',
																'type' => 'select',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '33',
																	'class' => '',
																	'id' => '',
																),
																'choices' => array(
																	'give' => 'Daj przedmiot',
																	'take' => 'Zabierz przedmiot',
																),
																'default_value' => 'give',
																'return_format' => 'value',
																'multiple' => 0,
																'allow_null' => 0,
																'allow_in_bindings' => 0,
																'ui' => 0,
																'ajax' => 0,
																'placeholder' => '',
																'allow_custom' => 0,
																'search_placeholder' => '',
															),
															array(
																'key' => 'field_item_select',
																'label' => 'Przedmiot',
																'name' => 'item',
																'aria-label' => '',
																'type' => 'post_object',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '33',
																	'class' => '',
																	'id' => '',
																),
																'post_type' => array(
																	0 => 'item',
																),
																'post_status' => '',
																'taxonomy' => '',
																'return_format' => 'id',
																'multiple' => 0,
																'allow_null' => 0,
																'allow_in_bindings' => 0,
																'ui' => 1,
																'bidirectional' => 0,
																'bidirectional_target' => array(),
															),
															array(
																'key' => 'field_item_quantity',
																'label' => 'Ilość',
																'name' => 'quantity',
																'aria-label' => '',
																'type' => 'number',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '33',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => 1,
																'min' => 1,
																'max' => '',
																'allow_in_bindings' => 0,
																'placeholder' => '',
																'step' => 1,
																'prepend' => '',
																'append' => '',
															),
														),
														'min' => '',
														'max' => '',
														'acfe_flexible_render_template' => '',
														'acfe_flexible_render_style' => '',
														'acfe_flexible_render_script' => '',
														'acfe_flexible_modal_edit_size' => '',
														'acfe_flexible_thumbnail' => false,
														'acfe_flexible_settings' => false,
														'acfe_flexible_settings_size' => 'medium',
														'acfe_flexible_category' => false,
													),
												),
												'min' => '',
												'max' => '',
												'button_label' => 'Dodaj wiersz',
												'acfe_flexible_empty_message' => '',
												'acfe_flexible_layouts_state' => false,
											),
											array(
												'key' => 'field_67b4e9d72acba',
												'label' => 'Po kliknięciu przejdź do ID',
												'name' => 'go_to_id',
												'aria-label' => '',
												'type' => 'acfe_slug',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '20',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
												'allow_in_bindings' => 0,
											),
										),
										'min' => '',
										'max' => '',
										'acfe_flexible_render_template' => '',
										'acfe_flexible_render_style' => '',
										'acfe_flexible_render_script' => '',
										'acfe_flexible_settings' => array(
											0 => 'group_start_rozmowy',
										),
										'acfe_flexible_settings_size' => 'xlarge',
										'acfe_flexible_thumbnail' => false,
										'acfe_flexible_modal_edit_size' => false,
										'acfe_flexible_category' => false,
									),
								),
								'min' => '',
								'max' => '',
								'button_label' => 'Dodaj odpowiedź',
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_settings' => array(
							0 => 'group_start_rozmowy',
						),
						'acfe_flexible_settings_size' => 'xlarge',
						'acfe_flexible_thumbnail' => '',
						'acfe_flexible_modal_edit_size' => false,
						'acfe_flexible_category' => false,
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Dodaj dialog',
				'acfe_flexible_hide_empty_message' => false,
				'acfe_flexible_empty_message' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'npc',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => 'Dialog',
		'acfe_autosync' => array(
			0 => 'php',
		),
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
		'modified' => 1744911027,
	));

endif;
