<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_user_settings',
        'title' => 'User',
        'fields' => array(
            array(
                'key' => 'field_tab_basic_info',
                'label' => 'Podstawowe informacje',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_679a2b8a1nick',
                'label' => 'Nick',
                'name' => 'nick',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Nazwa gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6794b4c86bae4',
                'label' => 'Avatar',
                'name' => 'avatar',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Obrazek postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50%',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'uploader' => '',
                'acfe_thumbnail' => 0,
            ),
            array(
                'key' => 'field_6794b4c86bae4_full',
                'label' => 'Avatar Full',
                'name' => 'avatar_full',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Pełny obrazek postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50%',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'preview_size' => 'medium',
                'min_width' => 0,
                'min_height' => 0,
                'min_size' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'max_size' => 0,
                'mime_types' => '',
                'uploader' => '',
                'acfe_thumbnail' => 0,
            ),
            array(
                'key' => 'field_679a2b8ab83a2',
                'label' => 'Story',
                'name' => 'story',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Tło fabularne postaci',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_679a2d06adef9',
                'label' => 'Klasa',
                'name' => 'user_class',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'zadymiarz' => 'Zadymiarz',
                    'zawijacz' => 'Zawijacz',
                    'kombinator' => 'Kombinator',
                ),
                'default_value' => false,
                'return_format' => 'array',
                'multiple' => 0,
                'allow_null' => 1,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            array(
                'key' => 'field_tab_stats',
                'label' => 'Statystyki',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_6793e6cb83c38',
                'label' => 'Statystyki',
                'name' => 'stats',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Podstawowe statystyki gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_stats_strength',
                        'label' => 'Siła',
                        'name' => 'strength',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Zwiększa obrażenia w walce wręcz i dominację w bójkach',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_stats_defense',
                        'label' => 'Wytrzymałość',
                        'name' => 'defense',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Zwiększa liczbę ciosów jakie mozemy przyjąć',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_stats_dexterity',
                        'label' => 'Zręczność',
                        'name' => 'dexterity',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Odpowiada za skuteczność kradzieży, uniki, ucieczki',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_stats_perception',
                        'label' => 'Percepcja',
                        'name' => 'perception',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Szansa na wykrycie ukrytych przedmiotów, NPC, opcji',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_stats_technical',
                        'label' => 'Zdolności manualne',
                        'name' => 'technical',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Efektywność produkcji (używki, towary), hakowanie, techniczne akcje',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_stats_charisma',
                        'label' => 'Cwaniactwo',
                        'name' => 'charisma',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Umiejętność bajerowania NPC, prowadzenia układów, handlu',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_progress_group',
                'label' => 'Postęp',
                'name' => 'progress',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Kontener na progress gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_progress_exp',
                        'label' => 'Doświadczenie',
                        'name' => 'exp',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Całkowity exp zdobyty przez gracza',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_progress_learning_points',
                        'label' => 'Punkty nauki',
                        'name' => 'learning_points',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Punkty do rozdania na statystyki',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 3,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_progress_reputation',
                        'label' => 'Reputacja',
                        'name' => 'reputation',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Reputacja gracza w mieście',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => -100,
                        'max' => 100,
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_vitality_group',
                'label' => 'Witalność',
                'name' => 'vitality',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Kontener na witalność gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6793e6cb83c39',
                        'label' => 'Życie',
                        'name' => 'life',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Aktualne życie gracza',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 100,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6793e6cb83c3a',
                        'label' => 'Maksymalne życie',
                        'name' => 'max_life',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Limit życia',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 100,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6793e6cb83c3b',
                        'label' => 'Energia',
                        'name' => 'energy',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Aktualna energia',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 100,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6793e6cb83c3b_max',
                        'label' => 'Maksymalna energia',
                        'name' => 'max_energy',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Limit energii',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 100,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_tab_skills',
                'label' => 'Umiejętności',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_skills_group',
                'label' => 'Umiejętności',
                'name' => 'skills',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_skills_combat',
                        'label' => 'Walka',
                        'name' => 'combat',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Zwiększa obrażenia, inicjatywę',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_skills_steal',
                        'label' => 'Kradzież',
                        'name' => 'steal',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Większa skuteczność, mniejsze ryzyko',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_skills_craft',
                        'label' => 'Produkcja',
                        'name' => 'craft',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Krótszy czas, więcej towaru',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_skills_trade',
                        'label' => 'Handel',
                        'name' => 'trade',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Lepsze ceny, więcej zarobku',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_skills_relations',
                        'label' => 'Relacje',
                        'name' => 'relations',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Bonusy, unikalne misje',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_skills_street',
                        'label' => 'Uliczna wiedza',
                        'name' => 'street',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Dostęp do sekretnych przejść, schowków',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_tab_location',
                'label' => 'Lokalizacja',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_current_area',
                'label' => 'Aktualny rejon',
                'name' => 'current_area',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => 'Aktualna lokalizacja gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'tereny',
                ),
                'taxonomy' => '',
                'allow_null' => 1,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
                'bidirectional_target' => array(),
                'save_custom' => 0,
                'save_post_type' => '',
                'save_post_status' => '',
            ),
            array(
                'key' => 'field_available_areas',
                'label' => 'Dostępne rejony',
                'name' => 'available_areas',
                'aria-label' => '',
                'type' => 'checkbox',
                'instructions' => 'Zaznacz rejony dostępne dla gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    329 => 'Dostępny rejon Kolejowa',
                    207 => 'Dostępny rejon Park',
                    24 => 'Dostępny rejon start',
                ),
                'default_value' => array(),
                'return_format' => 'value',
                'allow_custom' => 0,
                'layout' => 'vertical',
                'save_custom' => 0,
                'custom_choice_button_text' => 'Dodaj nowy wybór',
                'toggle' => 0,
            ),
            array(
                'key' => 'field_tab_equipped_items',
                'label' => 'Przedmioty',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_6793e69183c31',
                'label' => 'Plecak',
                'name' => 'backpack',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Kontener na przedmioty gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6793e6a783c33',
                        'label' => 'Złote',
                        'name' => 'gold',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Główna waluta',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6793e69b83c32',
                        'label' => 'Papierosy',
                        'name' => 'cigarettes',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => 'Alternatywna waluta',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => 0,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_equipped_items_group',
                'label' => 'Założone przedmioty',
                'name' => 'equipped_items',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => 'Przedmioty aktualnie założone przez gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_equipped_item_chest',
                        'label' => 'Na klatę',
                        'name' => 'chest_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na klatę',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:3',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                    array(
                        'key' => 'field_equipped_item_bottom',
                        'label' => 'Na poślady',
                        'name' => 'bottom_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na poślady',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:4',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                    array(
                        'key' => 'field_equipped_item_legs',
                        'label' => 'Na giczuły',
                        'name' => 'legs_item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => 'Przedmiot założony na giczuły',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => array(
                            0 => 'item_type:7',
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_items_inventory',
                'label' => 'Przedmioty',
                'name' => 'items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => 'Lista przedmiotów posiadanych przez gracza',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Dodaj przedmiot',
                'rows_per_page' => 20,
                'acfe_repeater_stylised_button' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_item_relation',
                        'label' => 'Przedmiot',
                        'name' => 'item',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'item',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'object',
                        'ui' => 1,
                        'bidirectional_target' => array(),
                        'save_custom' => 0,
                        'save_post_type' => '',
                        'save_post_status' => '',
                        'parent_repeater' => 'field_items_inventory',
                    ),
                    array(
                        'key' => 'field_item_quantity',
                        'label' => 'Ilość',
                        'name' => 'quantity',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 1,
                        'min' => 1,
                        'max' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_items_inventory',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_role',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => array(
            0 => 'php',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
        'modified' => 1746461798,
    ));

endif;
