<?php

/**
 * ACF Component: Item Action
 * 
 * Komponent reprezentujący akcję przedmiotu w odpowiedzi dialogowej.
 */

return array(
    'key' => 'layout_item_management',
    'name' => 'item',
    'label' => 'Przedmiot',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_item_action',
            'label' => 'Akcja',
            'name' => 'item_action',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'give' => 'Daj przedmiot',
                'take' => 'Zabierz przedmiot',
            ),
            'default_value' => 'give',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        array(
            'key' => 'field_item_select',
            'label' => 'Przedmiot',
            'name' => 'item',
            'aria-label' => '',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'item',
            ),
            'post_status' => '',
            'taxonomy' => '',
            'return_format' => 'id',
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 1,
            'bidirectional' => 0,
            'bidirectional_target' => array(),
        ),
        array(
            'key' => 'field_item_quantity',
            'label' => 'Ilość',
            'name' => 'quantity',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'min' => 1,
            'max' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'step' => 1,
            'prepend' => '',
            'append' => '',
        ),
    ),
    'min' => '',
    'max' => '',
    'acfe_flexible_render_template' => '',
    'acfe_flexible_render_style' => '',
    'acfe_flexible_render_script' => '',
    'acfe_flexible_modal_edit_size' => '',
    'acfe_flexible_thumbnail' => false,
    'acfe_flexible_settings' => false,
    'acfe_flexible_settings_size' => 'medium',
    'acfe_flexible_category' => false,
);
