<?php
// Rejestracja CPT "NPC"
function register_cpt_npc()
{
    register_post_type('npc', array(
        'labels' => array(
            'name'               => 'NPC',
            'singular_name'      => 'NPC',
            'menu_name'          => 'NPC',
            'all_items'          => 'Wszystkie NPC',
            'edit_item'          => 'Edytuj NPC',
            'view_item'          => 'Zobacz NPC',
            'add_new_item'       => 'Dodaj nowy NPC',
            'new_item'           => 'Nowy NPC',
            'search_items'       => 'Szukaj NPCów',
            'not_found'          => 'Nie znaleziono NPCów',
            'not_found_in_trash' => 'Nie znaleziono NPCów w koszu',
        ),
        'public'        => false,
        'show_ui'       => true,
        'show_in_menu'  => true,
        'supports'      => array('title', 'thumbnail'),
        'has_archive'   => false,
        'menu_position' => 5,
        'menu_icon'     => 'dashicons-admin-users',
        'show_in_rest'  => false,
    ));
}
add_action('init', 'register_cpt_npc');


if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_NPC',
        'title' => 'Dane NPC',
        'fields' => array(
            array(
                'key' => 'field_67b08ae59dc59',
                'label' => 'Start rozmowy',
                'name' => 'conversation_start',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Dodaj warunek',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_67b08af09dc5a',
                        'label' => 'Jeśli',
                        'name' => 'if',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'mission' => 'Misja',
                            'scena' => 'Scena',
                            'instance' => 'Instancja',
                            'relation' => 'Relacja',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                    array(
                        'key' => 'field_67b08fcbf1563',
                        'label' => 'Misja',
                        'name' => 'mission_select',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_67b08af09dc5a',
                                    'operator' => '==',
                                    'value' => 'mission',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67b08ba89dc5b',
                                'label' => 'Misja',
                                'name' => 'mission',
                                'aria-label' => '',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'tereny',
                                ),
                                'post_status' => '',
                                'taxonomy' => '',
                                'return_format' => 'object',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'bidirectional' => 0,
                                'ui' => 1,
                                'bidirectional_target' => array(),
                            ),
                            array(
                                'key' => 'field_67b08e96fffbe',
                                'label' => 'Jest ukończona',
                                'name' => 'is_end',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 0,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                        ),
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                    array(
                        'key' => 'field_67b08bc79dc5c',
                        'label' => 'Scena',
                        'name' => 'scena',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_67b08af09dc5a',
                                    'operator' => '==',
                                    'value' => 'scena',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => 'jest równa',
                        'append' => '',
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                    array(
                        'key' => 'field_67b08c0c9dc5d',
                        'label' => 'Instancja',
                        'name' => 'instation',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_67b08af09dc5a',
                                    'operator' => '==',
                                    'value' => 'instance',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => 'jest równa',
                        'append' => '',
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                    array(
                        'key' => 'field_67b0901df1565',
                        'label' => 'Relacja',
                        'name' => 'relation_select',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_67b08af09dc5a',
                                    'operator' => '==',
                                    'value' => 'relation',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67b08c2b9dc5e',
                                'label' => 'Relacja',
                                'name' => 'relacja',
                                'aria-label' => '',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'npc',
                                ),
                                'post_status' => '',
                                'taxonomy' => '',
                                'return_format' => 'id',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'bidirectional' => 0,
                                'ui' => 1,
                                'bidirectional_target' => array(),
                            ),
                            array(
                                'key' => 'field_67b08c829dc5f',
                                'label' => 'Operator',
                                'name' => 'operator',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    '>' => '>',
                                    '>=' => '>=',
                                    '=' => '=',
                                    '<' => '<',
                                    '=>' => '=>',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_67b08cab9dc60',
                                'label' => 'Wartość',
                                'name' => 'value',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                    array(
                        'key' => 'field_67b08bc79dcasdasw2',
                        'label' => 'To zacznij rozmowę od sceny dialogowej',
                        'name' => 'when_start_conversation',
                        'aria-label' => '',
                        'type' => 'text',
                        // 'instructions' => 'To zacznij rozmowę od sceny dialogowej',
                        'required' => 0,
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_67b08ae59dc59',
                    ),
                ),
            ),
            array(
                'key' => 'field_6794avatr_npc',
                'label' => 'Avatar',
                'name' => 'big_avatar',
                'type' => 'image',
                'required' => 0,
                'conditional_logic' => 0,
                'return_format' => 'array',
                'library' => 'all',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_wrapper_chat',
                'label' => 'Odpowiedzi',
                'name' => 'wrapper_chat',
                'type' => 'repeater',
                'button_label' => 'Dodaj konwersację',
                'instructions' => 'Dodaj możliwe odpowiedzi do tego pytania.',
                'min' => 1,
                'max' => 5,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_scena_dialogowa',
                        'label' => 'Scena dialogowa',
                        'name' => 'scena_dialogowa',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_67afbe46c8395',
                        'label' => 'Konwersacje',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'accordion',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'open' => 0,
                        'multi_expand' => 0,
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_conversation',
                        'label' => 'Konwersacja',
                        'name' => 'conversation',
                        'type' => 'repeater',
                        'button_label' => 'Dodaj pytanie',
                        'instructions' => 'Dodaj pytania i odpowiedzi do konwersacji.',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'sub_fields' => array(

                            array(
                                'key' => 'field_question',
                                'label' => 'Pytanie',
                                'name' => 'question',
                                'type' => 'wysiwyg',
                                'instructions' => 'Treść pytania.',
                                'required' => 1,
                                'tabs' => 'all',
                                'toolbar' => 'basic',
                                'media_upload' => 0,
                                'delay' => 0,
                            ),
                            array(
                                'key' => 'field_answers',
                                'label' => 'Odpowiedzi',
                                'name' => 'answers',
                                'type' => 'repeater',
                                'button_label' => 'Dodaj odpowiedź',
                                'instructions' => 'Dodaj możliwe odpowiedzi do tego pytania.',
                                'min' => 1,
                                'max' => 5,
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_answer_visibility',
                                        'label' => 'Widoczność odpowiedzi',
                                        'name' => 'answer_visibility',
                                        'type' => 'select',
                                        'choices' => array(
                                            'always' => 'Wyświetlaj zawsze',
                                            'conditional' => 'Wyświetlaj warunkowo',
                                        ),
                                        'default_value' => 'always',
                                        'return_format' => 'value',
                                        'wrapper' => array(
                                            'width' => '100',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_answer_conditions',
                                        'label' => 'Warunki wyświetlania',
                                        'name' => 'answer_conditions',
                                        'type' => 'repeater',
                                        'button_label' => 'Dodaj warunek',
                                        'instructions' => 'Dodaj warunki, które muszą być spełnione, by odpowiedź była widoczna.',
                                        'layout' => 'block',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_answer_visibility',
                                                    'operator' => '==',
                                                    'value' => 'conditional',
                                                ),
                                            ),
                                        ),
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_answer_if',
                                                'label' => 'Jeśli',
                                                'name' => 'if',
                                                'type' => 'select',
                                                'choices' => array(
                                                    'mission' => 'Misja',
                                                    'scena' => 'Scena',
                                                    'instance' => 'Instancja',
                                                    'relation' => 'Relacja',
                                                ),
                                                'default_value' => false,
                                                'return_format' => 'value',
                                                'wrapper' => array(
                                                    'width' => '30',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_answer_mission_select',
                                                'label' => 'Misja',
                                                'name' => 'mission_select',
                                                'type' => 'group',
                                                'wrapper' => array(
                                                    'width' => '70',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_answer_if',
                                                            'operator' => '==',
                                                            'value' => 'mission',
                                                        ),
                                                    ),
                                                ),
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_answer_mission',
                                                        'label' => 'Misja',
                                                        'name' => 'mission',
                                                        'type' => 'post_object',
                                                        'post_type' => array('misja'),
                                                        'return_format' => 'object',
                                                        'multiple' => 0,
                                                        'allow_null' => 0,
                                                        'wrapper' => array(
                                                            'width' => '50',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                    ),
                                                    array(
                                                        'key' => 'field_answer_is_end',
                                                        'label' => 'Jest ukończona',
                                                        'instructions' => "Misja musi być przypisana do usera",
                                                        'name' => 'is_end',
                                                        'type' => 'true_false',
                                                        'default_value' => 0,
                                                        'wrapper' => array(
                                                            'width' => '50',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_answer_scena',
                                                'label' => 'Scena',
                                                'name' => 'scena',
                                                'type' => 'text',
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_answer_if',
                                                            'operator' => '==',
                                                            'value' => 'scena',
                                                        ),
                                                    ),
                                                ),
                                                'wrapper' => array(
                                                    'width' => '70',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'prepend' => 'jest równa',
                                            ),
                                            array(
                                                'key' => 'field_answer_instance',
                                                'label' => 'Instancja',
                                                'name' => 'instation',
                                                'type' => 'text',
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_answer_if',
                                                            'operator' => '==',
                                                            'value' => 'instance',
                                                        ),
                                                    ),
                                                ),
                                                'wrapper' => array(
                                                    'width' => '70',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'prepend' => 'jest równa',
                                            ),
                                            array(
                                                'key' => 'field_answer_relation_select',
                                                'label' => 'Relacja',
                                                'name' => 'relation_select',
                                                'type' => 'group',
                                                'wrapper' => array(
                                                    'width' => '70',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_answer_if',
                                                            'operator' => '==',
                                                            'value' => 'relation',
                                                        ),
                                                    ),
                                                ),
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_answer_relacja',
                                                        'label' => 'Relacja',
                                                        'name' => 'relacja',
                                                        'type' => 'post_object',
                                                        'post_type' => array('npc'),
                                                        'return_format' => 'object',
                                                        'multiple' => 0,
                                                        'allow_null' => 0,
                                                        'wrapper' => array(
                                                            'width' => '33',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                    ),
                                                    array(
                                                        'key' => 'field_answer_operator',
                                                        'label' => 'Operator',
                                                        'name' => 'operator',
                                                        'type' => 'select',
                                                        'wrapper' => array(
                                                            'width' => '33',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            '>' => '>',
                                                            '>=' => '>=',
                                                            '=' => '=',
                                                            '<' => '<',
                                                            '<=' => '<=',
                                                        ),
                                                        'default_value' => '=',
                                                    ),
                                                    array(
                                                        'key' => 'field_answer_value',
                                                        'label' => 'Wartość',
                                                        'name' => 'value',
                                                        'type' => 'text',
                                                        'wrapper' => array(
                                                            'width' => '33',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),


                                    array(
                                        'key' => 'field_answer_text',
                                        'label' => 'Tekst odpowiedzi',
                                        'name' => 'answer_text',
                                        'type' => 'text',
                                        'required' => 1,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_next_question',
                                        'label' => 'ID kolejnego pytania',
                                        'name' => 'next_question',
                                        'type' => 'number',
                                        'instructions' => 'Wpisz ID kolejnego pytania (lub 0, by zakończyć).',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_answers',
                                'label' => 'Odpowiedzi',
                                'name' => 'answers',
                                'type' => 'repeater',
                                'button_label' => 'Dodaj odpowiedź',
                                'instructions' => 'Dodaj możliwe odpowiedzi do tego pytania.',
                                'min' => 1,
                                'max' => 5,
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_answer_text',
                                        'label' => 'Tekst odpowiedzi',
                                        'name' => 'answer_text',
                                        'type' => 'text',
                                        'required' => 1,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_next_question',
                                        'label' => 'ID kolejnego pytania',
                                        'name' => 'next_question',
                                        'type' => 'number',
                                        'instructions' => 'Wpisz ID kolejnego pytania (lub 0, by zakończyć).',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_67ab9655ea305',
                                        'label' => 'Typ pytania',
                                        'name' => 'question_type',
                                        'type' => 'select',
                                        'choices' => array(
                                            'default'           => 'Nic nie rób',
                                            'transaction'       => 'Transakcja',
                                            'from_group'        => 'Z grupy',
                                            'function'          => 'Funkcja',
                                        ),
                                        'default_value' => 'default',
                                        'return_format' => 'value',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_67ab9655ea305_function',
                                        'label' => 'Funkcja',
                                        'name' => 'function',
                                        'aria-label' => '',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'choices' => array(
                                            'default' => 'Nic nie rób',
                                            'SetClass' => 'Wybierz klasę',
                                        ),
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => false,
                                        'return_format' => 'value',
                                        'multiple'    => 0,
                                        'allow_null'  => 0,
                                        'ui'          => 0,
                                        'ajax'        => 0,
                                        'placeholder' => '',
                                        'parent_repeater' => 'field_67ab9613ea303',
                                        'conditional_logic' => array(
                                            array(
                                                'field'    => 'field_67ab9655ea305',
                                                'operator' => '==',
                                                'value'    => 'function',
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_67afaa9fdd159',
                                        'label' => 'Parametry funkcji',
                                        'name' => 'function_parametr',
                                        'aria-label' => '',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'pagination' => 0,
                                        'min' => 0,
                                        'max' => 0,
                                        'collapsed' => '',
                                        'button_label' => 'Dodaj parametr',
                                        'rows_per_page' => 20,
                                        'conditional_logic' => array(
                                            array(
                                                'field'    => 'field_67ab9655ea305',
                                                'operator' => '==',
                                                'value'    => 'function',
                                            ),
                                        ),
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_67afaab1dd15a',
                                                'label' => 'Nazwa',
                                                'name' => 'name',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'parent_repeater' => 'field_67afaa9fdd159',
                                            ),
                                            array(
                                                'key' => 'field_67afaac3dd15b',
                                                'label' => 'Wartość',
                                                'name' => 'value',
                                                'aria-label' => '',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'maxlength' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'parent_repeater' => 'field_67afaa9fdd159',
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_67ab975e97e31',
                                        'label' => 'Transakcja',
                                        'name' => 'transaction',
                                        'type' => 'repeater',
                                        'button_label' => 'Dodaj transakcje',
                                        'instructions' => 'Zdefiniuj elementy transakcji.',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field'    => 'field_67ab9655ea305',
                                                    'operator' => '==',
                                                    'value'    => 'transaction',
                                                ),
                                            ),
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_67ab9961cd299',
                                                'label' => 'Rodzaj',
                                                'name' => 'transaction_type',
                                                'type' => 'select',
                                                'allow_null' => 1,
                                                'required' => 1,
                                                'choices' => array(
                                                    'bag'    => 'Towar',
                                                    'relation' => 'Relacja',
                                                ),
                                                'wrapper' => array(
                                                    'width' => '33',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                // 'default_value' => 'bag',
                                            ),
                                            array(
                                                'key' => 'field_67abcde123fgh',
                                                'label' => 'Relacja z',
                                                'name' => 'relation_target',
                                                'type' => 'select',
                                                'allow_null' => 1,
                                                'choices' => array(
                                                    'npc'  => 'NPC',
                                                    'user' => 'Użytkownik',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67ab9961cd299',
                                                            'operator' => '==',
                                                            'value' => 'relation',
                                                        ),
                                                    ),
                                                ),
                                                'wrapper' => array(
                                                    'width' => '25',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_67ab996bagsadas',
                                                'label' => 'Towar',
                                                'name' => 'bag',
                                                'aria-label' => '',
                                                'type' => 'select',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'allow_null' => 1,
                                                'wrapper' => array(
                                                    'width' => '25',
                                                    'class' => '',
                                                    'id'    => '',
                                                ),
                                                'choices' => array(
                                                    'gold'       => 'Hajs',
                                                    'papierosy'  => 'Szlugi',
                                                    'piwo'       => 'Browar',
                                                    'bimber'     => 'Bimber',
                                                    'marihuana'  => 'Marihuana',
                                                    'grzyby'     => 'Grzyby',
                                                    'klej'       => 'Klej',
                                                ),
                                                'default_value' => false,
                                                'return_format' => 'value',
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67ab9961cd299',
                                                            'operator' => '==',
                                                            'value' => 'bag',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_67ab98ffcd298',
                                                'label' => 'Dodaj/zabierz',
                                                'name' => 'add_remove',
                                                'aria-label' => '',
                                                'type' => 'number',
                                                'instructions' => 'Napisz ile chcesz zabrać lub dodać towaru. Minus odbiera, liczba dodatnia dodaje.',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67ab9961cd299',
                                                            'operator' => '==',
                                                            'value' => 'bag',
                                                        ),
                                                    ),
                                                ),
                                                'wrapper' => array(
                                                    'width' => '25',
                                                    'class' => '',
                                                    'id' => '',
                                                ),

                                            ),

                                            array(
                                                'key' => 'field_67abcde456ijk',
                                                'label' => 'Wybierz NPC',
                                                'name' => 'target_npc',
                                                'type' => 'post_object',
                                                'return_format' => 'value',
                                                'post_type' => array('npc'),
                                                'wrapper' => array(
                                                    'width' => '50',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67abcde123fgh',
                                                            'operator' => '==',
                                                            'value' => 'npc',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_67abcde789lmn',
                                                'label' => 'Wybierz użytkownika',
                                                'name' => 'target_user',
                                                'type' => 'user',
                                                'wrapper' => array(
                                                    'width' => '25',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67abcde123fgh',
                                                            'operator' => '==',
                                                            'value' => 'user',
                                                        ),
                                                    ),
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_67abaa789f3b3',
                                                'label' => 'Zmiana relacji',
                                                'name' => 'relation_change',
                                                'type' => 'range',
                                                'instructions' => 'Ustaw wartość dodatnią dla poprawienia relacji, ujemną dla pogorszenia.',
                                                'min'           => -20,
                                                'max'           => 20,
                                                'default_value' => NULL,
                                                'wrapper' => array(
                                                    'width' => '25',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'conditional_logic' => array(
                                                    array(
                                                        array(
                                                            'field' => 'field_67ab9961cd299',
                                                            'operator' => '==',
                                                            'value' => 'relation',
                                                        ),
                                                    ),
                                                ),
                                            ),


                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),

            ),
        ),
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'npc',
                ),
            ),
        ),
        'hide_on_screen' => array('the_content'),
        'active'        => true,
        'show_in_rest'  => 0,
    ));
}
// add_filter('acf/load_field/key=field_67abcde456ijk', function ($field) {
//     if (isset($_GET['post']) && is_admin()) {
//         $field['default_value'] = intval($_GET['post']);
//     }
//     return $field;
// });



if (function_exists('acf_add_local_field_group')) {
    $fields_relacja = array();
    foreach (get_users() as $user) {
        $fields_relacja[] = array(
            'key'           => 'npc-relation-user-' . $user->ID,
            'label'         => 'Relacja z ' . $user->user_login,
            'name'          => 'npc-relation-user-' . $user->ID,
            'type'          => 'range',
            'min'           => -100,
            'max'           => 100,
            'default_value' => 0,
        );
    }
    acf_add_local_field_group(array(
        'key' => 'group_relacja_z_graczami',
        'title' => 'relacja z graczami',
        'fields' => $fields_relacja,
        'location' => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'npc',
                ),
            ),
        ),
        'hide_on_screen' => array('the_content'),
        'active'        => true,
        'show_in_rest'  => 0,
    ));
}
