<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_mission',
        'title' => 'Misje',
        'fields' => array(
            array(
                'key' => 'field_mission_info',
                'label' => 'Informacje o misji',
                'name' => 'mission_info',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mission_type',
                        'label' => 'Typ misji',
                        'name' => 'mission_type',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'choices' => array(
                            'story' => 'Fabularna',
                            'daily' => 'Dzienna',
                            'side' => 'Poboczna',
                        ),
                        'default_value' => 'story',
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'field_mission_giver',
                        'label' => 'Zleceniodawca',
                        'name' => 'mission_giver',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'post_type' => 'npc',
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'field_mission_description',
                        'label' => 'Opis misji',
                        'name' => 'mission_description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 5,
                        'new_lines' => 'br',
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_mission_tasks',
                'label' => 'Zadania',
                'name' => 'mission_tasks',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_flexible_advanced' => 1,
                'acfe_flexible_stylised_button' => 1,
                'acfe_flexible_layouts_templates' => 1,
                'layouts' => array(
                    'layout_mission_task' => array(
                        'key' => 'layout_mission_task',
                        'name' => 'task',
                        'label' => 'Zadanie',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_task_id',
                                'label' => 'ID zadania',
                                'name' => 'task_id',
                                'type' => 'acfe_slug',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array(
                                'key' => 'field_task_title',
                                'label' => 'Nazwa zadania',
                                'name' => 'task_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '70',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array(
                                'key' => 'field_task_description',
                                'label' => 'Opis zadania',
                                'name' => 'task_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_task_type',
                                'label' => 'Typ zadania',
                                'name' => 'task_type',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'choices' => array(
                                    'dialog' => 'Dialog z NPC',
                                    'item' => 'Zbierz przedmiot',
                                    'sell' => 'Sprzedaj przedmiot',
                                    'place' => 'Odwiedź miejsce',
                                    'custom' => 'Niestandardowe',
                                ),
                                'default_value' => 'dialog',
                                'wrapper' => array(
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array(
                                'key' => 'field_task_dialog',
                                'label' => 'Dialog',
                                'name' => 'task_dialog',
                                'type' => 'flexible_content',
                                'instructions' => '',
                                'required' => 0,
                                'button_label' => 'Dodaj dialog',
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_task_type',
                                            'operator' => '==',
                                            'value' => 'dialog',
                                        ),
                                    ),
                                ),
                                'acfe_flexible_advanced' => 1,
                                'layouts' => array(
                                    'layout_task_dialog' => array(
                                        'key' => 'layout_task_dialog',
                                        'name' => 'dialog',
                                        'label' => 'Dialog',
                                        'display' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_dialog_npc',
                                                'label' => 'NPC',
                                                'name' => 'dialog_npc',
                                                'type' => 'post_object',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'post_type' => 'npc',
                                                'taxonomy' => '',
                                                'allow_null' => 0,
                                                'multiple' => 0,
                                                'return_format' => 'id',
                                                'wrapper' => array(
                                                    'width' => '50',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_dialog_question',
                                                'label' => 'Pytanie/Kwestia NPC',
                                                'name' => 'dialog_question',
                                                'type' => 'wysiwyg',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'tabs' => 'all',
                                                'toolbar' => 'full',
                                                'media_upload' => 0,
                                                'delay' => 0,
                                            ),
                                            array(
                                                'key' => 'field_dialog_responses',
                                                'label' => 'Odpowiedzi',
                                                'name' => 'dialog_responses',
                                                'type' => 'flexible_content',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'button_label' => 'Dodaj odpowiedź',
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'acfe_flexible_advanced' => 1,
                                                'layouts' => array(
                                                    'layout_response' => array(
                                                        'key' => 'layout_response',
                                                        'name' => 'response',
                                                        'label' => 'Odpowiedź',
                                                        'display' => 'block',
                                                        'sub_fields' => array(
                                                            array(
                                                                'key' => 'field_response_text',
                                                                'label' => 'Treść odpowiedzi',
                                                                'name' => 'response_text',
                                                                'type' => 'text',
                                                                'instructions' => '',
                                                                'required' => 1,
                                                                'conditional_logic' => 0,
                                                                'wrapper' => array(
                                                                    'width' => '30',
                                                                    'class' => '',
                                                                    'id' => '',
                                                                ),
                                                            ),
                                                            array(
                                                                'key' => 'field_response_conditions',
                                                                'label' => 'Warunki wyświetlenia',
                                                                'name' => 'response_conditions',
                                                                'type' => 'flexible_content',
                                                                'instructions' => '',
                                                                'required' => 0,
                                                                'button_label' => 'Dodaj warunek',
                                                                'conditional_logic' => 0,
                                                                'wrapper' => array(
                                                                    'width' => '70',
                                                                    'class' => '',
                                                                    'id' => '',
                                                                ),
                                                                'acfe_flexible_advanced' => 1,
                                                                'acfe_flexible_modal_edit' => array(
                                                                    'acfe_flexible_modal_edit_enabled' => '1',
                                                                    'acfe_flexible_modal_edit_size' => 'large',
                                                                ),
                                                                'layouts' => array(
                                                                    'layout_condition_item' => array(
                                                                        'key' => 'layout_condition_item',
                                                                        'name' => 'condition_item',
                                                                        'label' => 'Przedmiot',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_condition_item_id',
                                                                                'label' => 'Przedmiot',
                                                                                'name' => 'condition_item_id',
                                                                                'type' => 'post_object',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'post_type' => 'item',
                                                                                'return_format' => 'id',
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_item_count',
                                                                                'label' => 'Ilość',
                                                                                'name' => 'condition_item_count',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 1,
                                                                                'min' => 1,
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_condition_class' => array(
                                                                        'key' => 'layout_condition_class',
                                                                        'name' => 'condition_class',
                                                                        'label' => 'Klasa postaci',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_condition_class_name',
                                                                                'label' => 'Klasa',
                                                                                'name' => 'condition_class_name',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'sebix' => 'Sebix',
                                                                                    'dresik' => 'Dresik',
                                                                                    'cwaniak' => 'Cwaniak',
                                                                                    'ziomek' => 'Ziomek',
                                                                                    'gangus' => 'Gangus',
                                                                                ),
                                                                                'wrapper' => array(
                                                                                    'width' => '100',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_condition_skill' => array(
                                                                        'key' => 'layout_condition_skill',
                                                                        'name' => 'condition_skill',
                                                                        'label' => 'Umiejętność',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_condition_skill_name',
                                                                                'label' => 'Umiejętność',
                                                                                'name' => 'condition_skill_name',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'walka' => 'Walka',
                                                                                    'spryt' => 'Spryt',
                                                                                    'odpornosc' => 'Odporność',
                                                                                    'inteligencja' => 'Inteligencja',
                                                                                    'charyzma' => 'Charyzma',
                                                                                ),
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_skill_operator',
                                                                                'label' => 'Operator',
                                                                                'name' => 'condition_skill_operator',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'greater' => '>',
                                                                                    'greaterEqual' => '>=',
                                                                                    'equal' => '=',
                                                                                    'less' => '<',
                                                                                    'lessEqual' => '<=',
                                                                                ),
                                                                                'default_value' => 'greater',
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_skill_value',
                                                                                'label' => 'Wartość',
                                                                                'name' => 'condition_skill_value',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 0,
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_condition_stat' => array(
                                                                        'key' => 'layout_condition_stat',
                                                                        'name' => 'condition_stat',
                                                                        'label' => 'Statystyka',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_condition_stat_name',
                                                                                'label' => 'Statystyka',
                                                                                'name' => 'condition_stat_name',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'szacun' => 'Szacun',
                                                                                    'exp' => 'Doświadczenie',
                                                                                ),
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_stat_operator',
                                                                                'label' => 'Operator',
                                                                                'name' => 'condition_stat_operator',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'greater' => '>',
                                                                                    'greaterEqual' => '>=',
                                                                                    'equal' => '=',
                                                                                    'less' => '<',
                                                                                    'lessEqual' => '<=',
                                                                                ),
                                                                                'default_value' => 'greater',
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_stat_value',
                                                                                'label' => 'Wartość',
                                                                                'name' => 'condition_stat_value',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 0,
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_condition_mission' => array(
                                                                        'key' => 'layout_condition_mission',
                                                                        'name' => 'condition_mission',
                                                                        'label' => 'Status misji/zadania',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_condition_mission_id',
                                                                                'label' => 'ID misji/zadania',
                                                                                'name' => 'condition_mission_id',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(),
                                                                                'ui' => 1,
                                                                                'ajax' => 1,
                                                                                'return_format' => 'value',
                                                                                'placeholder' => '',
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_task_id',
                                                                                'label' => 'ID zadania (opcjonalnie)',
                                                                                'name' => 'condition_task_id',
                                                                                'type' => 'text',
                                                                                'instructions' => 'Wpisz ID zadania (pole task_id) jeśli chcesz sprawdzić status konkretnego zadania',
                                                                                'required' => 0,
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_condition_mission_status',
                                                                                'label' => 'Status',
                                                                                'name' => 'condition_mission_status',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'completed' => 'Ukończona',
                                                                                    'taskCompleted' => 'Zadanie ukończone',
                                                                                    'inprogress' => 'W trakcie',
                                                                                    'notstarted' => 'Nierozpoczęta',
                                                                                    'failed' => 'Nieudana',
                                                                                ),
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                            array(
                                                                'key' => 'field_response_effects',
                                                                'label' => 'Efekty odpowiedzi',
                                                                'name' => 'response_effects',
                                                                'type' => 'flexible_content',
                                                                'button_label' => 'Dodaj efekt odpowiedzi',
                                                                'instructions' => '',
                                                                'required' => 0,
                                                                'conditional_logic' => 0,
                                                                'wrapper' => array(
                                                                    'width' => '',
                                                                    'class' => '',
                                                                    'id' => '',
                                                                ),
                                                                'acfe_flexible_advanced' => 1,
                                                                'acfe_flexible_modal_edit' => array(
                                                                    'acfe_flexible_modal_edit_enabled' => '1',
                                                                    'acfe_flexible_modal_edit_size' => 'large',
                                                                ),
                                                                'layouts' => array(
                                                                    'layout_effect_item' => array(
                                                                        'key' => 'layout_effect_item',
                                                                        'name' => 'effect_item',
                                                                        'label' => 'Przedmiot',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_effect_item_id',
                                                                                'label' => 'Przedmiot',
                                                                                'name' => 'effect_item_id',
                                                                                'type' => 'post_object',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'post_type' => 'item',
                                                                                'return_format' => 'id',
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_effect_item_action',
                                                                                'label' => 'Akcja',
                                                                                'name' => 'effect_item_action',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'add' => 'Dodaj',
                                                                                    'remove' => 'Usuń',
                                                                                ),
                                                                                'default_value' => 'add',
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_effect_item_count',
                                                                                'label' => 'Ilość',
                                                                                'name' => 'effect_item_count',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 1,
                                                                                'min' => 1,
                                                                                'wrapper' => array(
                                                                                    'width' => '33',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_effect_stat' => array(
                                                                        'key' => 'layout_effect_stat',
                                                                        'name' => 'effect_stat',
                                                                        'label' => 'Statystyka',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_effect_stat_name',
                                                                                'label' => 'Statystyka',
                                                                                'name' => 'effect_stat_name',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'szacun' => 'Szacun',
                                                                                    'exp' => 'Doświadczenie',
                                                                                ),
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_effect_stat_value',
                                                                                'label' => 'Wartość',
                                                                                'name' => 'effect_stat_value',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 0,
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_effect_task' => array(
                                                                        'key' => 'layout_effect_task',
                                                                        'name' => 'effect_task',
                                                                        'label' => 'Aktualizacja zadania',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_effect_task_id',
                                                                                'label' => 'ID zadania',
                                                                                'name' => 'effect_task_id',
                                                                                'type' => 'text',
                                                                                'instructions' => 'ID zadania w tej misji',
                                                                                'required' => 1,
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_effect_task_status',
                                                                                'label' => 'Status',
                                                                                'name' => 'effect_task_status',
                                                                                'type' => 'select',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'choices' => array(
                                                                                    'completed' => 'Ukończone',
                                                                                    'finished' => 'Zakończone',
                                                                                    'failed' => 'Nieudane',
                                                                                    'inprogress' => 'W trakcie',
                                                                                ),
                                                                                'default_value' => 'completed',
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                    'layout_effect_relation' => array(
                                                                        'key' => 'layout_effect_relation',
                                                                        'name' => 'effect_relation',
                                                                        'label' => 'Zmiana relacji z NPC',
                                                                        'display' => 'block',
                                                                        'sub_fields' => array(
                                                                            array(
                                                                                'key' => 'field_effect_relation_npc',
                                                                                'label' => 'NPC',
                                                                                'name' => 'effect_relation_npc',
                                                                                'type' => 'post_object',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'post_type' => 'npc',
                                                                                'return_format' => 'id',
                                                                                'wrapper' => array(
                                                                                    'width' => '100',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                            array(
                                                                                'key' => 'field_effect_relation_value',
                                                                                'label' => 'Zmiana',
                                                                                'name' => 'effect_relation_value',
                                                                                'type' => 'number',
                                                                                'instructions' => '',
                                                                                'required' => 1,
                                                                                'default_value' => 0,
                                                                                'wrapper' => array(
                                                                                    'width' => '50',
                                                                                    'class' => '',
                                                                                    'id' => '',
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_task_item',
                                'label' => 'Przedmiot',
                                'name' => 'task_item',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_task_type',
                                            'operator' => '==',
                                            'value' => 'item',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_task_item_id',
                                        'label' => 'Przedmiot',
                                        'name' => 'task_item_id',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 1,
                                        'post_type' => 'item',
                                        'return_format' => 'id',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_task_item_count',
                                        'label' => 'Ilość',
                                        'name' => 'task_item_count',
                                        'type' => 'number',
                                        'instructions' => '',
                                        'required' => 1,
                                        'default_value' => 1,
                                        'min' => 1,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_task_item_recipient_npc',
                                        'label' => 'NPC',
                                        'name' => 'task_item_recipient_npc',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_task_item_recipient_type',
                                                    'operator' => '==',
                                                    'value' => 'npc',
                                                ),
                                            ),
                                        ),
                                        'post_type' => 'npc',
                                        'return_format' => 'id',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_task_sell',
                                'label' => 'Sprzedaż przedmiotu',
                                'name' => 'task_sell',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_task_type',
                                            'operator' => '==',
                                            'value' => 'sell',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_task_sell_item',
                                        'label' => 'Przedmiot',
                                        'name' => 'task_sell_item',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 1,
                                        'post_type' => 'item',
                                        'return_format' => 'id',
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_task_sell_count',
                                        'label' => 'Ilość',
                                        'name' => 'task_sell_count',
                                        'type' => 'number',
                                        'instructions' => '',
                                        'required' => 1,
                                        'default_value' => 1,
                                        'min' => 1,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_task_sell_targets',
                                        'label' => 'Dostępni kupcy',
                                        'name' => 'task_sell_targets',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Dodaj potencjalnego kupca',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_task_sell_target_npc',
                                                'label' => 'NPC',
                                                'name' => 'task_sell_target_npc',
                                                'type' => 'post_object',
                                                'instructions' => '',
                                                'required' => 1,
                                                'post_type' => 'npc',
                                                'return_format' => 'id',
                                                'wrapper' => array(
                                                    'width' => '30',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_task_sell_target_valid',
                                                'label' => 'Prawidłowy',
                                                'name' => 'task_sell_target_valid',
                                                'type' => 'true_false',
                                                'instructions' => 'Czy jest to właściwa osoba do sprzedaży',
                                                'required' => 0,
                                                'default_value' => 0,
                                                'ui' => 1,
                                                'wrapper' => array(
                                                    'width' => '20',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_task_sell_target_dialog',
                                                'label' => 'Dialog przy sprzedaży',
                                                'name' => 'task_sell_target_dialog',
                                                'type' => 'wysiwyg',
                                                'instructions' => 'Tekst dialogu wyświetlany podczas sprzedaży temu NPC',
                                                'required' => 0,
                                                'default_value' => '',
                                                'tabs' => 'all',
                                                'toolbar' => 'full',
                                                'media_upload' => 0,
                                                'delay' => 0,
                                                'wrapper' => array(
                                                    'width' => '50',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_task_place_id',
                                'label' => 'Miejsce',
                                'name' => 'task_place_id',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_task_type',
                                            'operator' => '==',
                                            'value' => 'place',
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_task_custom',
                                'label' => 'Niestandardowe zadanie',
                                'name' => 'task_custom',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_task_type',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_task_custom_code',
                                        'label' => 'Kod PHP',
                                        'name' => 'task_custom_code',
                                        'type' => 'acfe_code_editor',
                                        'instructions' => 'Kod PHP do sprawdzenia czy zadanie zostało wykonane',
                                        'required' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '<?php
// Dostępne zmienne:
// $user_id - ID użytkownika
// $mission_id - ID misji
// $task_id - ID zadania
// 
// Funkcja powinna zwracać true jeśli zadanie zostało wykonane, false w przeciwnym wypadku
return false;
?>',
                                        'placeholder' => '',
                                        'mode' => 'php',
                                        'theme' => 'monokai',
                                        'rows' => 8,
                                        'max_rows' => '',
                                        'min_rows' => '',
                                        'font_size' => 14,
                                        'tab_size' => 4,
                                        'wrap' => 0,
                                        'readonly' => 0,
                                        'allow_in_bindings' => 0,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Dodaj nowe zadanie do misji',
            ),
            array(
                'key' => 'field_mission_rewards',
                'label' => 'Nagrody',
                'name' => 'mission_rewards',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mission_reward_exp',
                        'label' => 'Doświadczenie',
                        'name' => 'mission_reward_exp',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'default_value' => 0,
                        'min' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'field_mission_reward_szacun',
                        'label' => 'Szacun',
                        'name' => 'mission_reward_szacun',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'default_value' => 0,
                        'min' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'field_mission_reward_kasa',
                        'label' => 'Kasa',
                        'name' => 'mission_reward_kasa',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'default_value' => 0,
                        'min' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'field_mission_reward_relations',
                        'label' => 'Zmiana relacji z NPC',
                        'name' => 'mission_reward_relations',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Dodaj zmianę relacji z NPC',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mission_reward_relation_npc',
                                'label' => 'NPC',
                                'name' => 'mission_reward_relation_npc',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 1,
                                'post_type' => 'npc',
                                'return_format' => 'id',
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array(
                                'key' => 'field_mission_reward_relation_value',
                                'label' => 'Wartość',
                                'name' => 'mission_reward_relation_value',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 1,
                                'default_value' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_mission_reward_items',
                        'label' => 'Przedmioty',
                        'name' => 'mission_reward_items',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Dodaj przedmiot do nagród',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mission_reward_item_id',
                                'label' => 'Przedmiot',
                                'name' => 'mission_reward_item_id',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 1,
                                'post_type' => 'item',
                                'return_format' => 'id',
                                'wrapper' => array(
                                    'width' => '70',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array(
                                'key' => 'field_mission_reward_item_count',
                                'label' => 'Ilość',
                                'name' => 'mission_reward_item_count',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 1,
                                'default_value' => 1,
                                'min' => 1,
                                'wrapper' => array(
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mission',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => array(
            0 => 'php',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));

endif;
